services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER: ${USER}
        UID: ${UID}
    volumes:
      - .:/home/${USER}/zig_tryout
    working_dir: /home/${USER}/zig_tryout
    stdin_open: true
    tty: true
    stop_grace_period: 0s
